### ISSUE TITLE
improvement: save to flash on ESP32 device

### ISSUE THREAD

**Issue by lleo19** [J-Pipe/Whole-House-Water-Monitoring#3]
Thank you for publishing this project.
I have a water meter that has 0.1 gallon per pulse output and everything seems to work as expected.

I am using an ESP32 development board as that is what I had available.
Since I use an ESP32 device, the esp8266_restore_from_flash instruction does not work and I cannot store permanently a starting number to the device.
I would like to store the number actually showing on the water meter as the starting count to the ESP device and send to HA the incremental changes. Any thoughts how to do this?

**Comment by J-Pipe** [comment]
I think the ESP32 is supposed to save to flash by default, so that should not be an issue. But like I said in the documentation, you have to call:
`esphome.water_flow_power_cycle_restore`
to actually restore the last saved value, because I could not easily get it to work in the on_boot automation.

To set an "initial" water usage value, you can call:
`esphome.water_flow_set_total_water_used { value : xxx }`

**Comment by lleo19** [comment]
thanks for your reply
by using the esphome.water_flow_set_total_water_used { value : xxx } service call I am able to set an initial value that increments with subsequent flow. If, however, I also use the  esphome.water_flow_power_cycle_restore service call regardless to what value was set earlier, the total water used sensor is returning to zero. I assumed that this happened since the write_to_flash instruction was commented out.
Will experiment more

**Comment by J-Pipe** [comment]
Sorry, which write_to_flash instruction is commented out?

Also, since we want to reduce the number of times we write to flash, it will only save the value after ten more gallons have flowed. After 10 gallons have passed, you should be able to call that service and it should restore it to the last saved value.

**Comment by lleo19** [comment]
I had to comment out the line below as would not compile for an ESP32 board



#  esp8266_restore_from_flash: true

thanks, L.



-----Original message-----

**Comment by J-Pipe** [comment]
Oh okay, sorry. Yeah that makes sense. So I think you should be able to test this by calling the set_total_water_used service with a value of like 19.9. Then run some water for a bit, until that number goes up to >20. Then call the restore service and you should see the usage be changed to 25 gallons.

**Comment by lleo19** [comment]
Hello,

So I can set the total_water_user counter to any value I like, but couple of time a day it resets to zero.

calling the restore service does not restore the value to what was.

Here is today in 2 graphs. ONe is showing the flow rate throughout the day, the other the cumulative gallons.

The day starts just over 1000 gallons and increases over time, but sometimes after 9AM was reset. I notices it at noon, and then adjusted back to that value. After 4PM it was reset again.

Do not see any errors regarding the ESP32 device, the wifi signal is not the best, so there are disconnects, but reconnects very quickly.

The device has battery and usb power from a 2A wallwart and have not lost power today.

It may be my device, did not see anything in the code that would case this.

Any thoughts?

Thanks a lot in advance.

















-----Original message-----

**Comment by J-Pipe** [comment]
I just now tested everything with an ESP32. Everything seems to work fine. When your ESP disconnects and reconnects to wifi, the water_used sensor will change to "unknown". Make sure you have setup an automation so that when the state is "unkown," it will call the "restore" service. Otherwise, the next time water starts running, it will reset the total_usage to 0.

You're problem is happening because, your ESP is not saving the global "saved_usage_count" to flash, for some reason. How old is your ESP32? Have you used it before? Maybe the flash is just be burnt out on it?
